### PR TITLE
Implement AJAX in mainManager

### PR DESCRIPTION
**Pull request by mangkoran**

### CODE REVIEW

**Review by psakurai — COMMENTED** [review]
eh nvm, faham faham

**Comment by mangkoran** [comment]
Actually It's not necessary to remove it. I will add it back tomorrow.

**Comment by mangkoran** [comment]
[`2ad4c4a` (#6)](https://github.com/psakurai/web-sch-proj-SCAS/pull/6/commits/2ad4c4a4d0a5b6011fff03af811ba7e70998b622) I also delete output from `config.php` because it will broke output from other php files that reference `config.php`.

**Comment by mangkoran** [comment]
Alright can merge now.

**Pull request merged**
